[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_install = true  # << Esse aqui diz ao Netlify pra não rodar "npm install"

[[plugins]]
  package = "@netlify/plugin-cache"

  [plugins.inputs]
    paths = ["node_modules", ".cache", "package-lock.json"]
