[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Este comando evita reinstalação se já houver node_modules
[context.production.environment]
  NPM_FLAGS = "--prefer-offline --no-audit"
